# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SystemSetup.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SystemSetupDialog(object):
    def setupUi(self, SystemSetupDialog):
        os.environ['QT_IM_MODULE'] = 'qtvirtualkeyboard'
        SystemSetupDialog.setObjectName("SystemSetupDialog")
        SystemSetupDialog.resize(400, 312)
        
        self.verticalLayoutWidget = QtWidgets.QWidget(SystemSetupDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 381, 251))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.i_am_host_cbox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.i_am_host_cbox.setObjectName("i_am_host_cbox")
        self.verticalLayout.addWidget(self.i_am_host_cbox)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.camera_list_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.camera_list_edit.setObjectName("camera_list_edit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.camera_list_edit)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.client_list_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.client_list_edit.setObjectName("client_list_edit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.client_list_edit)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayoutWidget = QtWidgets.QWidget(SystemSetupDialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 270, 381, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.save_system_setup_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.save_system_setup_btn.setObjectName("save_system_setup_btn")
        self.horizontalLayout.addWidget(self.save_system_setup_btn)
        self.cancel_system_setup_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.cancel_system_setup_btn.setDefault(False)
        self.cancel_system_setup_btn.setFlat(False)
        self.cancel_system_setup_btn.setObjectName("cancel_system_setup_btn")
        self.horizontalLayout.addWidget(self.cancel_system_setup_btn)

        self.retranslateUi(SystemSetupDialog)
        QtCore.QMetaObject.connectSlotsByName(SystemSetupDialog)

        QtGui.QGuiApplication.inputMethod().visibleChanged.connect(self.handleVisibleChanged)


    def retranslateUi(self, SystemSetupDialog):
        _translate = QtCore.QCoreApplication.translate
        SystemSetupDialog.setWindowTitle(_translate("SystemSetupDialog", "System Setup"))
        self.i_am_host_cbox.setText(_translate("SystemSetupDialog", "This is the host machine"))
        self.label.setText(_translate("SystemSetupDialog", "Camera List:"))
        self.camera_list_edit.setText(_translate("SystemSetupDialog", "CA0001,CA0002,CA0003,CA0004"))
        self.label_2.setText(_translate("SystemSetupDialog", "Clients:"))
        self.client_list_edit.setText(_translate("SystemSetupDialog", "localhost,localhost,192.168.0.101,192.168.0.102"))
        self.save_system_setup_btn.setText(_translate("SystemSetupDialog", "Save"))
        self.cancel_system_setup_btn.setText(_translate("SystemSetupDialog", "Cancel"))

    def handleVisibleChanged():
        if not QtGui.QGuiApplication.inputMethod().isVisible():
            print('test')
            return
        for w in QtGui.QGuiApplication.allWindows():
            if w.metaObject().className() == "QtVirtualKeyboard::InputView":
                keyboard = w.findChild(QtCore.QObject, "keyboard")
                if keyboard is not None:
                    r = w.geometry()
                    r.moveTop(keyboard.property("y"))
                    w.setMask(QtGui.QRegion(r))
                    return
